FROM rabbitmq:3.8-management

# Set JWT config
COPY advanced.config /etc/rabbitmq/advanced.config

# Enable Stomp and JWT
RUN rabbitmq-plugins enable rabbitmq_web_stomp rabbitmq_auth_backend_oauth2

EXPOSE 5672
EXPOSE 15672
EXPOSE 15674
EXPOSE 4369
EXPOSE 25672
EXPOSE 61613
EXPOSE 61614
